Wrote a really stupid configure script.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,3 +1,25 @@
 #!/usr/bin/env bash
 
-sed -i 's|$(error IMPL must be set)|IMPL=ENT_DEV_URANDOM|' Makefile
+log () {
+  echo "$@" >&2;
+}
+
+for impl in ENT_GETENTROPY_UNISTD \
+            ENT_GETENTROPY_SYSRANDOM \
+            ENT_GETRANDOM_SYSCALL \
+            ENT_DEV_URANDOM
+do
+    export IMPL=$impl
+
+    log "Trying IMPL=$IMPL"
+
+    if IMPL=$impl make >/dev/null 2>/dev/null
+    then sed -i 's|$(error IMPL must be set)|IMPL='"$impl"'|' Makefile
+         log "IMPL=$IMPL works"
+         exit 0
+    else log "IMPL=$IMPL failed"
+    fi
+done
+
+log "This shouldn't happen, something is broken."
+exit 1
